### ISSUE TITLE
some code comments

### ISSUE THREAD

**Issue by stchang** [kclapper/tally-extract#1]
Pretty clean code :)

- https://github.com/kclapper/tally-extract/blob/610baefd86ec7bc8106b49f057f7a0b80b643aab/src/cell.rkt#L11
Seems redundant with the call to `map`?

- https://github.com/kclapper/tally-extract/blob/610baefd86ec7bc8106b49f057f7a0b80b643aab/src/read-file.rkt#L39
Does `filter` do what you need here?

- https://github.com/kclapper/tally-extract/blob/610baefd86ec7bc8106b49f057f7a0b80b643aab/src/tally.rkt#L31
You can look into the concept of `curry`ing here

**Comment by kclapper** [comment]
Thanks professor!

1. Yes it is redundant, I've removed it. I probably just assumed map would get mad at me if I gave it an empty list but it makes sense that it just returns an empty list in that case. See f09423f
2. Filter does what I need and is much cleaner than what I was doing. I still need a predicate for filter but it's definition is simple and easy to understand. See c8ff1a1
3. Yes! I'd heard of this before but I couldn't remember what it was. After looking into it, it makes the code much more concise and simple. See c8ff1a1

Thank you for your suggestions! I also reorganized the project structure to use some of the packaging conventions in [your blog post](https://blog.racket-lang.org/2017/10/tutorial-creating-a-package.html), see c6ffbba. All of these changes come together in c8ff1a1.
